/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiGithubPushRouteImport } from './routes/api/github/push'
import { Route as ApiAuthUrlRouteImport } from './routes/api/auth/url'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubPushRoute = ApiGithubPushRouteImport.update({
  id: '/api/github/push',
  path: '/api/github/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUrlRoute = ApiAuthUrlRouteImport.update({
  id: '/api/auth/url',
  path: '/api/auth/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/url': typeof ApiAuthUrlRoute
  '/api/github/push': typeof ApiGithubPushRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/url': typeof ApiAuthUrlRoute
  '/api/github/push': typeof ApiGithubPushRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/url': typeof ApiAuthUrlRoute
  '/api/github/push': typeof ApiGithubPushRoute
  '/api/github/repos': typeof ApiGithubReposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/auth/callback'
    | '/api/auth/url'
    | '/api/github/push'
    | '/api/github/repos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/auth/callback'
    | '/api/auth/url'
    | '/api/github/push'
    | '/api/github/repos'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/auth/callback'
    | '/api/auth/url'
    | '/api/github/push'
    | '/api/github/repos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthUrlRoute: typeof ApiAuthUrlRoute
  ApiGithubPushRoute: typeof ApiGithubPushRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/push': {
      id: '/api/github/push'
      path: '/api/github/push'
      fullPath: '/api/github/push'
      preLoaderRoute: typeof ApiGithubPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/url': {
      id: '/api/auth/url'
      path: '/api/auth/url'
      fullPath: '/api/auth/url'
      preLoaderRoute: typeof ApiAuthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthUrlRoute: ApiAuthUrlRoute,
  ApiGithubPushRoute: ApiGithubPushRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
